### ISSUE TITLE
Unexpected blockage of multicast socket

### ISSUE THREAD

**Issue by therealryan** [step-security/harden-runner#228]
The testing for [my project](https://github.com/Mastercard/flow) involves running some toy services that use [multicast UDP to discover each other](https://github.com/Mastercard/flow/blob/main/example/app-framework/src/main/java/com/mastercard/test/flow/example/framework/Discovery.java).

This socket usage is not detected in audit mode ([example report](https://app.stepsecurity.io/github/Mastercard/flow/actions/runs/3874395483)), but it _is_ blocked when the suggested blocking egress-policy is put in place ([PR](https://github.com/Mastercard/flow/pull/195), [build](https://github.com/Mastercard/flow/actions/runs/3874667569/jobs/6606169087)). The build had to be cancelled when the relevant test hung, but the build logs shows:
```
Error: Exception in thread "Discovery advertise" java.io.UncheckedIOException: java.io.IOException: Operation not permitted (sendto failed)
	at com.mastercard.test.flow.example.framework.Discovery.lambda$advertise$0(Discovery.java:97)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.io.IOException: Operation not permitted (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at com.mastercard.test.flow.example.framework.Discovery.lambda$advertise$0(Discovery.java:84)
	... 1 more
```

I'm not at all sure whether multicast UDP presents an exfiltration risk in the context of a github action. Defaulting to blocking it is thus probably the correct position, but it'd be great if it showed up in the audit and could be added to the allowed operation set.

Cheers!

**Comment by varunsh-coder** [comment]
Thanks, @therealryan, for using harden runner and creating this issue. Let me investigate and get back to you. Thanks!

**Comment by varunsh-coder** [comment]
@h0x0er please investigate this. Thanks!

**Comment by komer3** [comment]
We're seeing what looks like the same class of issue in GitHub Actions when running `step-security/harden-runner` in `egress-policy: block` and creating a `kind` cluster.

In our case the failure happens during Docker/kind network setup, before the e2e suite starts, with:

`failed to advertise addresses: write ip ::1->ff02::1: sendmsg: operation not permitted`

Switching the job to `audit` let it proceed, so this appears specific to `block` mode.

Our current workaround is to pre-create the shared Docker `kind` network as IPv4-only before running kind/ctlptl, which avoids the failing IPv6 local multicast/address-advertisement path.

We're on `harden-runner v2.19.1`, and I haven't found a supported way to exempt this path while keeping `egress-policy: block`.
